### ISSUE TITLE
Is there any way to find stories by title?

### ISSUE THREAD

**Issue by GildedHonour** [karan/HackerNewsAPI#48]
A question, not a bug. Is there any way to find stories by title? Say, 

```
hn.get_stories(title='some title%)

# or

reg_exp = re.compile('something')
hn.get_stories(title=reg_exp)


```

**Comment by GildedHonour** [comment]
If not, can I retrieve all the stories by date, say, 20 days from now?

**Comment by karan** [comment]
No search is not supported.

**Comment by GildedHonour** [comment]
can I retrieve all the stories by date, say, 20 days from now?

**Comment by karan** [comment]
Not at this time
